// Open-MeteoのWMOコードを日本語に変換
export const weatherCodeMap = {
  0:  { label: "快晴",           emoji: "☀️" },
  1:  { label: "晴れ",           emoji: "🌤️" },
  2:  { label: "一部曇り",       emoji: "⛅" },
  3:  { label: "曇り",           emoji: "☁️" },
  45: { label: "霧",             emoji: "🌫️" },
  48: { label: "霧氷",           emoji: "🌫️" },
  51: { label: "小雨",           emoji: "🌦️" },
  53: { label: "雨",             emoji: "🌧️" },
  55: { label: "強い雨",         emoji: "🌧️" },
  61: { label: "小雨",           emoji: "🌦️" },
  63: { label: "雨",             emoji: "🌧️" },
  65: { label: "大雨",           emoji: "🌧️" },
  71: { label: "小雪",           emoji: "🌨️" },
  73: { label: "雪",             emoji: "❄️" },
  75: { label: "大雪",           emoji: "❄️" },
  80: { label: "にわか雨",       emoji: "🌦️" },
  81: { label: "にわか雨(強)",   emoji: "🌧️" },
  95: { label: "雷雨",           emoji: "⛈️" },
  99: { label: "雹を伴う雷雨",   emoji: "⛈️" },
};